### ISSUE TITLE
.step file 1230_Front_Panel

### ISSUE THREAD

**Issue by schablone** [Ultimaker/Ultimaker2#16]
Hey, I try to open different .step files with different CAD systems, but it does not work. Can anybody send me the CAD file ot the Ultmaker front door. Thanks.

**Comment by jorgebalaguer** [comment]
Wich cad format do you prefer?

**Comment by schablone** [comment]
Parasolid would be great. Step normally should also work.

**Comment by jorgebalaguer** [comment]
Solidworks repaired some broken surfaces. Let's try.
K.R.

Jorge J. Balaguer

2015-05-16 21:05 GMT+02:00 schablone <notifications@github.com>:

**Comment by schablone** [comment]
You can send me a email to schablone666@web.de

thank you.
