### ISSUE TITLE
The top print head files were overwritten with a fan model

### ISSUE THREAD

**Issue by DefProc** [Ultimaker/Ultimaker2#19]
Looking at the history of the [`1320_Print_Head_Top_(x1)`](https://github.com/Ultimaker/Ultimaker2/commits/master/1320_Print_Head_Top_(x1)) folder, The original print head top model and drawings were [overwritten](https://github.com/Ultimaker/Ultimaker2/commit/0f47097a1351a3b4d1144491b7c2aa4c25af8c69#diff-794dd673b76b3bcda85d08d2952000f0) by a fan model and drawing. 

It looks like the files in the folder should be restored to the versions present at 71ec0cd9765a7a3c208167f37ee3231b9a6c7462

**Comment by rruggiero** [comment]
I have this version from Jan 4, 2016.

Rick Ruggiero

m: 0450 025 425
e: rick.ruggiero@gmail.com

**Comment by harmawoldhuis** [comment]
I've replaced the files with the correct fans.
sorry for the mixup

harma
